import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  BadgeCheck,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Copy,
  CircleHelp,
  CircleUserRound,
  Compass,
  CreditCard,
  Download,
  Edit3,
  Eye,
  FileText,
  Gift,
  Heart,
  Headphones,
  History,
  Home,
  ImageIcon,
  Info,
  LayoutDashboard,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquareQuote,
  Minus,
  Package,
  PackagePlus,
  RefreshCw,
  ReceiptText,
  Search,
  SearchX,
  Settings,
  ShieldCheck,
  ShieldPlus,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  StarHalf,
  Trash2,
  Truck,
  UsersRound,
  Volume2,
  VolumeX,
  Wallet,
  X,
  Zap,
} from "lucide-react";

type SymbolIconProps = {
  name: string;
  className?: string;
  filled?: boolean;
  strokeWidth?: number;
  "aria-hidden"?: boolean;
};

const icons: Record<string, LucideIcon> = {
  account_circle: CircleUserRound,
  add: PackagePlus,
  add_box: PackagePlus,
  add_comment: MessageCircle,
  add_shopping_cart: ShoppingCart,
  analytics: BarChart3,
  article: FileText,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  block: X,
  bolt: Zap,
  broken_image: ImageIcon,
  calendar_month: Bell,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_sweep: Trash2,
  done_all: CheckCircle2,
  east: ArrowRight,
  eco: Sparkles,
  edit_square: Edit3,
  edit: Edit3,
  error: AlertTriangle,
  explore: Compass,
  expand_more: ChevronDown,
  favorite: Heart,
  format_quote: MessageSquareQuote,
  grade: Star,
  group: UsersRound,
  groups: UsersRound,
  chat_bubble: MessageCircle,
  chat_bubble_outline: MessageCircle,
  health_and_safety: ShieldPlus,
  headset_mic: Headphones,
  history: History,
  history_edu: BookOpen,
  home: Home,
  image: ImageIcon,
  info: Info,
  inventory: Package,
  inventory_2: Package,
  local_shipping: Truck,
  location_on: MapPin,
  location_off: MapPin,
  login: LogIn,
  logout: LogOut,
  loyalty: Heart,
  mark_email_unread: Mail,
  mail: Mail,
  menu: Menu,
  monitoring: BarChart3,
  more_vert: SlidersHorizontal,
  notifications: Bell,
  open_in_new: ArrowUpRight,
  paid: CreditCard,
  payments: CreditCard,
  person: CircleUserRound,
  psychiatry: Sparkles,
  rate_review: MessageCircle,
  refresh: RefreshCw,
  remove: Minus,
  receipt_long: ReceiptText,
  redeem: Gift,
  schedule: Bell,
  search: Search,
  search_off: SearchX,
  settings: Settings,
  share: ArrowRight,
  shopping_basket: ShoppingBag,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  star: Star,
  star_half: StarHalf,
  store: Store,
  support_agent: Headphones,
  swap_vert: ArrowDownUp,
  tune: SlidersHorizontal,
  trending_up: BarChart3,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  vital_signs: Activity,
  volume_off: VolumeX,
  volume_up: Volume2,
  warning: AlertTriangle,
  west: ArrowLeft,
  account_balance_wallet: Wallet,
  content_copy: Copy,
  download: Download,
};

const filledIcons = new Set(["favorite", "grade"]);

export default function SymbolIcon({
  name,
  className = "",
  filled,
  strokeWidth = 2,
  "aria-hidden": ariaHidden = true,
}: SymbolIconProps) {
  const normalizedName = String(name || "").trim();
  const Icon = icons[normalizedName] || CircleHelp;
  const shouldFill = filled ?? filledIcons.has(normalizedName);

  return (
    <Icon
      aria-hidden={ariaHidden}
      className={`inline-block h-[1em] w-[1em] shrink-0 align-[-0.125em] leading-none ${className}`}
      fill={shouldFill ? "currentColor" : "none"}
      focusable="false"
      strokeWidth={strokeWidth}
    />
  );
}
